
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Archivo
{

    public Archivo()
    {

        this.EXACTUS_CABECERA_SIS = new HashSet<EXACTUS_CABECERA_SIS>();

        this.NOMINAs = new HashSet<NOMINA>();

        this.HistorialCargaArchivoes = new HashSet<HistorialCargaArchivo>();

        this.HistorialCargaArchivo_LinCab = new HashSet<HistorialCargaArchivo_LinCab>();

        this.EXACTUS_DETALLE_EXPORT_SIS = new HashSet<EXACTUS_DETALLE_EXPORT_SIS>();

    }


    public int ArchivoId { get; set; }

    public int EstadoArchivoId { get; set; }

    public int TipoArchivoId { get; set; }

    public string NombreArchivo { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<bool> Vigente { get; set; }

    public Nullable<System.DateTime> FechaAprobacion { get; set; }



    public virtual ICollection<EXACTUS_CABECERA_SIS> EXACTUS_CABECERA_SIS { get; set; }

    public virtual ICollection<NOMINA> NOMINAs { get; set; }

    public virtual ICollection<HistorialCargaArchivo> HistorialCargaArchivoes { get; set; }

    public virtual ICollection<HistorialCargaArchivo_LinCab> HistorialCargaArchivo_LinCab { get; set; }

    public virtual EstadoArchivo EstadoArchivo { get; set; }

    public virtual ICollection<EXACTUS_DETALLE_EXPORT_SIS> EXACTUS_DETALLE_EXPORT_SIS { get; set; }

    public virtual TipoArchivo TipoArchivo { get; set; }

}

}
