
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class CheckList
{

    public int CheckListId { get; set; }

    public string CUSPP { get; set; }

    public int TipoMovimientoId { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<bool> Vigente { get; set; }

    public Nullable<int> TipoSolicitudId { get; set; }

    public Nullable<int> Estado { get; set; }

    public string Observaciones { get; set; }

}

}
