
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class CONCEPTO
{

    public int ID_CONCEPTO { get; set; }

    public int IDE_IMPRESA { get; set; }

    public string TIPO_TABLA { get; set; }

    public string CODIGO { get; set; }

    public string DESCRIPCION { get; set; }

    public string VALOR { get; set; }

    public string CLASE { get; set; }

    public string TIPO { get; set; }

    public string ESTADO { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public string USU_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }

    public Nullable<int> IS_EDITABLE { get; set; }

}

}
