
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRATO
{

    public Nullable<int> ID_EMPRESA { get; set; }

    public int IDE_CONTRATO { get; set; }

    public string NRO_CONTRATO { get; set; }

    public string COD_RAMO_PRI { get; set; }

    public string COD_RAMO_SIN { get; set; }

    public string CLA_CONTRATO { get; set; }

    public System.DateTime FEC_INI_VIG { get; set; }

    public System.DateTime FEC_FIN_VIG { get; set; }

    public string TIP_CONTRATO { get; set; }

    public string COD_MONEDA { get; set; }

    public string COD_CONTRATANTE { get; set; }

    public Nullable<decimal> POR_PARTICIPA_CIA { get; set; }

    public Nullable<decimal> POR_TASA_RIESGO { get; set; }

    public Nullable<decimal> POR_TASA_REASEGURO { get; set; }

    public string CENTRO_COSTO { get; set; }

    public Nullable<decimal> POR_IMPUESTO { get; set; }

    public string DES_CONTRATO { get; set; }

    public string MOD_CONTRATO { get; set; }

    public Nullable<decimal> POR_RETENCION { get; set; }

    public Nullable<decimal> POR_CESION { get; set; }

    public Nullable<decimal> MTO_MAX_RETENCION { get; set; }

    public Nullable<decimal> MTO_MAX_CESION { get; set; }

    public Nullable<decimal> MTO_PLENO { get; set; }

    public Nullable<int> NRO_LINEA_MULT { get; set; }

    public Nullable<decimal> MTO_MAX_CUBERTURA { get; set; }

    public Nullable<int> NRO_CAPA_XL1 { get; set; }

    public Nullable<decimal> PRIORIDAD1 { get; set; }

    public Nullable<decimal> CESION_EXC_PRIORIDAD1 { get; set; }

    public Nullable<decimal> MTO_MAX_CAP_LIM_SUP1 { get; set; }

    public Nullable<decimal> PRIMA_MIN_DEPOSITO1 { get; set; }

    public Nullable<int> NRO_CAPA_XL2 { get; set; }

    public Nullable<decimal> PRIORIDAD2 { get; set; }

    public Nullable<decimal> CESION_EXC_PRIORIDAD2 { get; set; }

    public Nullable<decimal> MTO_MAX_CAP_LIM_SUP2 { get; set; }

    public Nullable<decimal> PRIMA_MIN_DEPOSITO2 { get; set; }

    public string ESTADO { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public string USU_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }

}

}
