
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRATO_SIS_DET
{

    public int IDE_CONTRATO_DET { get; set; }

    public Nullable<int> IDE_CONTRATO { get; set; }

    public Nullable<int> COD_CSV { get; set; }

    public Nullable<decimal> PRC_PARTICIACION { get; set; }

    public Nullable<int> NRO_ORDEN { get; set; }

    public string ESTADO { get; set; }

    public string USU_REG { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }



    public virtual CONTRATO_SYS CONTRATO_SYS { get; set; }

}

}
