
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class DATO_A
{

    public int IDE_EMPRESA { get; set; }

    public string NRO_CONTRATO { get; set; }

    public int ANIO_VIGENTE { get; set; }

    public int MES_VIGENTE { get; set; }

    public string TIPO_INFO { get; set; }

    public string COD_RAMO { get; set; }

    public int COD_PRODUCTO { get; set; }

    public string COD_ASEGURADO { get; set; }

    public string COD_MONEDA { get; set; }

    public string AP_MTNO_PENS { get; set; }

    public string AP_MTNO_SOLIC { get; set; }

    public string AP_PTNO_PENS { get; set; }

    public string AP_PTNO_SOLIC { get; set; }

    public Nullable<decimal> APORT_COMP { get; set; }

    public Nullable<decimal> APORT_OBLIG { get; set; }

    public Nullable<decimal> CAP_REQ_PENS { get; set; }

    public Nullable<decimal> CAP_REQ_SEPE { get; set; }

    public Nullable<decimal> CIC_MON_NSOL { get; set; }

    public Nullable<decimal> CIC_MON_ORIG { get; set; }

    public Nullable<decimal> CRU_FAMILIAR { get; set; }

    public string CUSPP { get; set; }

    public string FE_SIN { get; set; }

    public string ID_AFP { get; set; }

    public Nullable<int> ID_COD_CSV1 { get; set; }

    public Nullable<int> ID_COD_CSV2 { get; set; }

    public Nullable<int> ID_COD_CSV3 { get; set; }

    public Nullable<int> ID_COD_CSV4 { get; set; }

    public Nullable<int> ID_COD_TRANSF { get; set; }

    public Nullable<int> ID_TIP_SOLI { get; set; }

    public Nullable<decimal> MTO_PAGO_CSV1 { get; set; }

    public Nullable<decimal> MTO_PAGO_CSV2 { get; set; }

    public Nullable<decimal> MTO_PAGO_CSV3 { get; set; }

    public Nullable<decimal> MTO_PAGO_CSV4 { get; set; }

    public string TI_MOV { get; set; }

    public string FE_DEV { get; set; }

    public string FE_FALLE { get; set; }

    public string FE_INI_INV { get; set; }

    public string FE_PAG_AA { get; set; }

    public Nullable<int> ID_TIP_DOC { get; set; }

    public string IND_PENS_PRE { get; set; }

    public Nullable<decimal> MTO_AA_MON_NSOL { get; set; }

    public Nullable<decimal> MTO_AA_MON_ORIG { get; set; }

    public Nullable<decimal> MTO_EXC_MON_NSOL { get; set; }

    public Nullable<decimal> MTO_EXC_MON_ORIG { get; set; }

    public Nullable<decimal> MTO_PENS_PRE_MON_NSOL { get; set; }

    public Nullable<decimal> MTO_PENS_PRE_MON_ORIG { get; set; }

    public string NRO_BENEF { get; set; }

    public string NRO_IDEN_SOLIC { get; set; }

    public string NUM_CSV { get; set; }

    public string PRI_NOMB_SOLIC { get; set; }

    public Nullable<decimal> RAM_PROM_NSOL { get; set; }

    public string SEGU_NOMB_SOLIC { get; set; }

    public Nullable<decimal> TASA_INT { get; set; }

    public Nullable<decimal> TI_CAMB_COMPRA { get; set; }

    public Nullable<decimal> TI_CAMB_VTA { get; set; }

    public string TI_REG { get; set; }

    public Nullable<int> TIP_MON { get; set; }

    public string TIP_PEN_EQUIV { get; set; }

    public Nullable<decimal> TOT_CAP_REQ_MON_NSOL { get; set; }

    public Nullable<decimal> TOT_CAP_REQ_MON_ORIG { get; set; }

    public Nullable<decimal> DESCT_PENS { get; set; }

    public Nullable<decimal> DESCT_PENS_CSV1 { get; set; }

    public Nullable<decimal> DESCT_PENS_CSV2 { get; set; }

    public Nullable<decimal> DESCT_PENS_CSV3 { get; set; }

    public Nullable<decimal> DESCT_PENS_CSV4 { get; set; }

    public string FE_DEV_ACT { get; set; }

    public string FE_DEV_INI { get; set; }

    public string FE_FIN_SUBSI { get; set; }

    public string FE_NACI_PENS { get; set; }

    public string FE_SECI { get; set; }

    public string FEC_PAGO { get; set; }

    public string FRAC_MES_DEV { get; set; }

    public string ID_COD_BEN { get; set; }

    public Nullable<int> ID_PARENT { get; set; }

    public string ID_TIP_DOCU_PENS { get; set; }

    public string MES_DEV { get; set; }

    public string MON_EQUI { get; set; }

    public Nullable<decimal> MTO_APORT_COMP_CSV1 { get; set; }

    public Nullable<decimal> MTO_APORT_COMP_CSV2 { get; set; }

    public Nullable<decimal> MTO_APORT_COMP_CSV3 { get; set; }

    public Nullable<decimal> MTO_APORT_COMP_CSV4 { get; set; }

    public Nullable<decimal> MTO_APORT_OBLIG_CSV1 { get; set; }

    public Nullable<decimal> MTO_APORT_OBLIG_CSV2 { get; set; }

    public Nullable<decimal> MTO_APORT_OBLIG_CSV3 { get; set; }

    public Nullable<decimal> MTO_APORT_OBLIG_CSV4 { get; set; }

    public Nullable<decimal> MTO_PAGO { get; set; }

    public string NRO_DOCU_PENS { get; set; }

    public string NRO_EESS { get; set; }

    public string NRO_MES_DEV { get; set; }

    public Nullable<int> NRO_SIN { get; set; }

    public string NRO_SOLI { get; set; }

    public Nullable<decimal> PENS_BASE { get; set; }

    public Nullable<decimal> PENS_PAGAR_80 { get; set; }

    public string PRI_NOMB_PENS { get; set; }

    public string PROC_BENE { get; set; }

    public Nullable<decimal> PROM_ACT_6_MESES_APOCOMP { get; set; }

    public Nullable<decimal> REMPRO_ACT { get; set; }

    public string SEGU_NOMB_PENS { get; set; }

    public string TIP_PEN { get; set; }

    public string ESTADO { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public string USU_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }

}

}
