

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class DISEntities : DbContext
{
    public DISEntities()
        : base("name=DISEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CIERRE_PROCESO> CIERRE_PROCESOs { get; set; }

    public virtual DbSet<CONCEPTO> CONCEPTOs { get; set; }

    public virtual DbSet<CONTRATO> CONTRATOs { get; set; }

    public virtual DbSet<CONTRATO_SIS_DET> CONTRATO_SIS_DETs { get; set; }

    public virtual DbSet<CONTRATO_SYS> CONTRATO_SYSs { get; set; }

    public virtual DbSet<DATO_M> DATO_Ms { get; set; }

    public virtual DbSet<Evento> Eventos { get; set; }

    public virtual DbSet<Exactu> Exactus { get; set; }

    public virtual DbSet<EXACTUS_CABECERA_SIS> EXACTUS_CABECERA_SISs { get; set; }

    public virtual DbSet<EXACTUS_DETALLE> EXACTUS_DETALLEs { get; set; }

    public virtual DbSet<EXACTUS_DETALLE_SIS> EXACTUS_DETALLE_SISs { get; set; }

    public virtual DbSet<GENERAL> GENERALs { get; set; }

    public virtual DbSet<LogOperacion> LogOperacions { get; set; }

    public virtual DbSet<NOMINA> NOMINAs { get; set; }

    public virtual DbSet<OPERACION> OPERACIONs { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<HistorialCargaArchivo> HistorialCargaArchivos { get; set; }

    public virtual DbSet<HistorialCargaArchivo_LinCab> HistorialCargaArchivo_LinCabs { get; set; }

    public virtual DbSet<HistorialCargaArchivo_LinDet> HistorialCargaArchivo_LinDets { get; set; }

    public virtual DbSet<ReglaArchivo> ReglaArchivos { get; set; }

    public virtual DbSet<AFP> AFPs { get; set; }

    public virtual DbSet<Archivo> Archivos { get; set; }

    public virtual DbSet<Bitacora> Bitacoras { get; set; }

    public virtual DbSet<Checkeado> Checkeados { get; set; }

    public virtual DbSet<ContratoCSV> ContratoCSVs { get; set; }

    public virtual DbSet<Contrato1> Contrato1s { get; set; }

    public virtual DbSet<Correlativo> Correlativos { get; set; }

    public virtual DbSet<CSV> CSVs { get; set; }

    public virtual DbSet<Documento> Documentos { get; set; }

    public virtual DbSet<DocumentoSolicitado> DocumentoSolicitados { get; set; }

    public virtual DbSet<EstadoArchivo> EstadoArchivos { get; set; }

    public virtual DbSet<EstadoPago> EstadoPagos { get; set; }

    public virtual DbSet<Imputacion> Imputacions { get; set; }

    public virtual DbSet<Moneda> Monedas { get; set; }

    public virtual DbSet<MontoAlto> MontoAltos { get; set; }

    public virtual DbSet<Pago> Pagos { get; set; }

    public virtual DbSet<Parametro> Parametros { get; set; }

    public virtual DbSet<Parentesco> Parentescos { get; set; }

    public virtual DbSet<Persona> Personas { get; set; }

    public virtual DbSet<RegistroMontoAlto> RegistroMontoAltos { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Siniestro> Siniestros { get; set; }

    public virtual DbSet<TipoArchivo> TipoArchivos { get; set; }

    public virtual DbSet<TipoCambio> TipoCambios { get; set; }

    public virtual DbSet<TipoDocumentoIdentificacion> TipoDocumentoIdentificacions { get; set; }

    public virtual DbSet<TipoInforme> TipoInformes { get; set; }

    public virtual DbSet<TipoMoneda> TipoMonedas { get; set; }

    public virtual DbSet<TipoMovimiento> TipoMovimientos { get; set; }

    public virtual DbSet<TipoPension> TipoPensions { get; set; }

    public virtual DbSet<TipoRegistro> TipoRegistros { get; set; }

    public virtual DbSet<TipoSolicitude> TipoSolicitudes { get; set; }

    public virtual DbSet<COMPROBANTE> COMPROBANTEs { get; set; }

    public virtual DbSet<Consulta> Consultas { get; set; }

    public virtual DbSet<CONTRATO_DETALLE> CONTRATO_DETALLEs { get; set; }

    public virtual DbSet<DATO_A> DATO_As { get; set; }

    public virtual DbSet<EXACTUS_CABECERA> EXACTUS_CABECERAs { get; set; }

    public virtual DbSet<EXACTUS_DETALLE_EXPORT_SIS> EXACTUS_DETALLE_EXPORT_SISs { get; set; }

    public virtual DbSet<USUARIO> USUARIOs { get; set; }

    public virtual DbSet<CheckList> CheckLists { get; set; }


    public virtual int pa_audit_InsertaBitacora(Nullable<int> param_IdUsuario, string param_Descripcion, string param_Comando, Nullable<int> param_Idarchivo)
    {

        var param_IdUsuarioParameter = param_IdUsuario.HasValue ?
            new ObjectParameter("Param_IdUsuario", param_IdUsuario) :
            new ObjectParameter("Param_IdUsuario", typeof(int));


        var param_DescripcionParameter = param_Descripcion != null ?
            new ObjectParameter("Param_Descripcion", param_Descripcion) :
            new ObjectParameter("Param_Descripcion", typeof(string));


        var param_ComandoParameter = param_Comando != null ?
            new ObjectParameter("Param_Comando", param_Comando) :
            new ObjectParameter("Param_Comando", typeof(string));


        var param_IdarchivoParameter = param_Idarchivo.HasValue ?
            new ObjectParameter("Param_Idarchivo", param_Idarchivo) :
            new ObjectParameter("Param_Idarchivo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_audit_InsertaBitacora", param_IdUsuarioParameter, param_DescripcionParameter, param_ComandoParameter, param_IdarchivoParameter);
    }


    public virtual ObjectResult<pa_devuelveresultado_Result> pa_devuelveresultado(Nullable<int> idarchivo)
    {

        var idarchivoParameter = idarchivo.HasValue ?
            new ObjectParameter("idarchivo", idarchivo) :
            new ObjectParameter("idarchivo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_devuelveresultado_Result>("pa_devuelveresultado", idarchivoParameter);
    }


    public virtual int pa_envioCorreo_Procesos(string para, string cC, string cCO, string asunto, string cuerpo, string formatoCuerpo, string archivos)
    {

        var paraParameter = para != null ?
            new ObjectParameter("Para", para) :
            new ObjectParameter("Para", typeof(string));


        var cCParameter = cC != null ?
            new ObjectParameter("CC", cC) :
            new ObjectParameter("CC", typeof(string));


        var cCOParameter = cCO != null ?
            new ObjectParameter("CCO", cCO) :
            new ObjectParameter("CCO", typeof(string));


        var asuntoParameter = asunto != null ?
            new ObjectParameter("Asunto", asunto) :
            new ObjectParameter("Asunto", typeof(string));


        var cuerpoParameter = cuerpo != null ?
            new ObjectParameter("Cuerpo", cuerpo) :
            new ObjectParameter("Cuerpo", typeof(string));


        var formatoCuerpoParameter = formatoCuerpo != null ?
            new ObjectParameter("FormatoCuerpo", formatoCuerpo) :
            new ObjectParameter("FormatoCuerpo", typeof(string));


        var archivosParameter = archivos != null ?
            new ObjectParameter("Archivos", archivos) :
            new ObjectParameter("Archivos", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_envioCorreo_Procesos", paraParameter, cCParameter, cCOParameter, asuntoParameter, cuerpoParameter, formatoCuerpoParameter, archivosParameter);
    }


    public virtual int pa_file_AgregaReferenciaTablaArchivo(string nombreArchivo)
    {

        var nombreArchivoParameter = nombreArchivo != null ?
            new ObjectParameter("NombreArchivo", nombreArchivo) :
            new ObjectParameter("NombreArchivo", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_AgregaReferenciaTablaArchivo", nombreArchivoParameter);
    }


    public virtual int pa_file_ArchivoValido(Nullable<int> idArchivo)
    {

        var idArchivoParameter = idArchivo.HasValue ?
            new ObjectParameter("IdArchivo", idArchivo) :
            new ObjectParameter("IdArchivo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_ArchivoValido", idArchivoParameter);
    }


    public virtual int pa_file_CierreCarga(Nullable<int> idCarga)
    {

        var idCargaParameter = idCarga.HasValue ?
            new ObjectParameter("IdCarga", idCarga) :
            new ObjectParameter("IdCarga", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_CierreCarga", idCargaParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_file_ConsultaEstadoArchivo(string nombreArchivo)
    {

        var nombreArchivoParameter = nombreArchivo != null ?
            new ObjectParameter("NombreArchivo", nombreArchivo) :
            new ObjectParameter("NombreArchivo", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_file_ConsultaEstadoArchivo", nombreArchivoParameter);
    }


    public virtual int pa_file_Imputa_Nomina(Nullable<int> idarchivo, Nullable<int> idusuario)
    {

        var idarchivoParameter = idarchivo.HasValue ?
            new ObjectParameter("idarchivo", idarchivo) :
            new ObjectParameter("idarchivo", typeof(int));


        var idusuarioParameter = idusuario.HasValue ?
            new ObjectParameter("idusuario", idusuario) :
            new ObjectParameter("idusuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_Imputa_Nomina", idarchivoParameter, idusuarioParameter);
    }


    public virtual int pa_file_InsertaHistorialCarga(Nullable<int> aux_IdArchivo, Nullable<int> aux_IdReglaArchivo, string aux_TipoLinea, Nullable<int> aux_NumeroLinea, Nullable<int> aux_CampoInicial, Nullable<int> aux_LargoCampo, string aux_ValorCampo, Nullable<int> aux_CumpleValidacion)
    {

        var aux_IdArchivoParameter = aux_IdArchivo.HasValue ?
            new ObjectParameter("Aux_IdArchivo", aux_IdArchivo) :
            new ObjectParameter("Aux_IdArchivo", typeof(int));


        var aux_IdReglaArchivoParameter = aux_IdReglaArchivo.HasValue ?
            new ObjectParameter("Aux_IdReglaArchivo", aux_IdReglaArchivo) :
            new ObjectParameter("Aux_IdReglaArchivo", typeof(int));


        var aux_TipoLineaParameter = aux_TipoLinea != null ?
            new ObjectParameter("Aux_TipoLinea", aux_TipoLinea) :
            new ObjectParameter("Aux_TipoLinea", typeof(string));


        var aux_NumeroLineaParameter = aux_NumeroLinea.HasValue ?
            new ObjectParameter("Aux_NumeroLinea", aux_NumeroLinea) :
            new ObjectParameter("Aux_NumeroLinea", typeof(int));


        var aux_CampoInicialParameter = aux_CampoInicial.HasValue ?
            new ObjectParameter("Aux_CampoInicial", aux_CampoInicial) :
            new ObjectParameter("Aux_CampoInicial", typeof(int));


        var aux_LargoCampoParameter = aux_LargoCampo.HasValue ?
            new ObjectParameter("Aux_LargoCampo", aux_LargoCampo) :
            new ObjectParameter("Aux_LargoCampo", typeof(int));


        var aux_ValorCampoParameter = aux_ValorCampo != null ?
            new ObjectParameter("Aux_ValorCampo", aux_ValorCampo) :
            new ObjectParameter("Aux_ValorCampo", typeof(string));


        var aux_CumpleValidacionParameter = aux_CumpleValidacion.HasValue ?
            new ObjectParameter("Aux_CumpleValidacion", aux_CumpleValidacion) :
            new ObjectParameter("Aux_CumpleValidacion", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_InsertaHistorialCarga", aux_IdArchivoParameter, aux_IdReglaArchivoParameter, aux_TipoLineaParameter, aux_NumeroLineaParameter, aux_CampoInicialParameter, aux_LargoCampoParameter, aux_ValorCampoParameter, aux_CumpleValidacionParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_file_InsertaReferenciaArchivo(string nombreArchivo, string usuarioModificacion)
    {

        var nombreArchivoParameter = nombreArchivo != null ?
            new ObjectParameter("NombreArchivo", nombreArchivo) :
            new ObjectParameter("NombreArchivo", typeof(string));


        var usuarioModificacionParameter = usuarioModificacion != null ?
            new ObjectParameter("usuarioModificacion", usuarioModificacion) :
            new ObjectParameter("usuarioModificacion", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_file_InsertaReferenciaArchivo", nombreArchivoParameter, usuarioModificacionParameter);
    }


    public virtual ObjectResult<pa_file_ObtieneErrorArchivo_Result> pa_file_ObtieneErrorArchivo(Nullable<int> idArchivo)
    {

        var idArchivoParameter = idArchivo.HasValue ?
            new ObjectParameter("IdArchivo", idArchivo) :
            new ObjectParameter("IdArchivo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_file_ObtieneErrorArchivo_Result>("pa_file_ObtieneErrorArchivo", idArchivoParameter);
    }


    public virtual ObjectResult<string> pa_file_ObtienePrimerCaracterLineaPorTipoArchivo(string param_TipoArchivo)
    {

        var param_TipoArchivoParameter = param_TipoArchivo != null ?
            new ObjectParameter("Param_TipoArchivo", param_TipoArchivo) :
            new ObjectParameter("Param_TipoArchivo", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_file_ObtienePrimerCaracterLineaPorTipoArchivo", param_TipoArchivoParameter);
    }


    public virtual ObjectResult<string> pa_file_ObtieneReglavalidacionArchivo(string archivo, Nullable<int> tipo)
    {

        var archivoParameter = archivo != null ?
            new ObjectParameter("Archivo", archivo) :
            new ObjectParameter("Archivo", typeof(string));


        var tipoParameter = tipo.HasValue ?
            new ObjectParameter("Tipo", tipo) :
            new ObjectParameter("Tipo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_file_ObtieneReglavalidacionArchivo", archivoParameter, tipoParameter);
    }


    public virtual ObjectResult<string> pa_file_ObtieneTipoArchivos()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_file_ObtieneTipoArchivos");
    }


    public virtual ObjectResult<pa_impactanegocio_Result> pa_impactanegocio(Nullable<int> idarchivo)
    {

        var idarchivoParameter = idarchivo.HasValue ?
            new ObjectParameter("idarchivo", idarchivo) :
            new ObjectParameter("idarchivo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_impactanegocio_Result>("pa_impactanegocio", idarchivoParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_impactanomina(Nullable<int> idnomina)
    {

        var idnominaParameter = idnomina.HasValue ?
            new ObjectParameter("idnomina", idnomina) :
            new ObjectParameter("idnomina", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_impactanomina", idnominaParameter);
    }


    public virtual int pa_imputa_aad(Nullable<int> idnomina, Nullable<int> idusuario)
    {

        var idnominaParameter = idnomina.HasValue ?
            new ObjectParameter("idnomina", idnomina) :
            new ObjectParameter("idnomina", typeof(int));


        var idusuarioParameter = idusuario.HasValue ?
            new ObjectParameter("idusuario", idusuario) :
            new ObjectParameter("idusuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_aad", idnominaParameter, idusuarioParameter);
    }


    public virtual int pa_imputa_ppp(Nullable<int> idnomina, Nullable<int> idusuario)
    {

        var idnominaParameter = idnomina.HasValue ?
            new ObjectParameter("idnomina", idnomina) :
            new ObjectParameter("idnomina", typeof(int));


        var idusuarioParameter = idusuario.HasValue ?
            new ObjectParameter("idusuario", idusuario) :
            new ObjectParameter("idusuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_ppp", idnominaParameter, idusuarioParameter);
    }


    public virtual int pa_imputa_ppr(Nullable<int> idnomina, Nullable<int> idusuario)
    {

        var idnominaParameter = idnomina.HasValue ?
            new ObjectParameter("idnomina", idnomina) :
            new ObjectParameter("idnomina", typeof(int));


        var idusuarioParameter = idusuario.HasValue ?
            new ObjectParameter("idusuario", idusuario) :
            new ObjectParameter("idusuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_ppr", idnominaParameter, idusuarioParameter);
    }


    public virtual int pa_imputa_prp(Nullable<int> idnomina, Nullable<int> idusuario)
    {

        var idnominaParameter = idnomina.HasValue ?
            new ObjectParameter("idnomina", idnomina) :
            new ObjectParameter("idnomina", typeof(int));


        var idusuarioParameter = idusuario.HasValue ?
            new ObjectParameter("idusuario", idusuario) :
            new ObjectParameter("idusuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_prp", idnominaParameter, idusuarioParameter);
    }


    public virtual int pa_imputa_rgs(Nullable<int> idnomina, Nullable<int> idusuario)
    {

        var idnominaParameter = idnomina.HasValue ?
            new ObjectParameter("idnomina", idnomina) :
            new ObjectParameter("idnomina", typeof(int));


        var idusuarioParameter = idusuario.HasValue ?
            new ObjectParameter("idusuario", idusuario) :
            new ObjectParameter("idusuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_rgs", idnominaParameter, idusuarioParameter);
    }


    public virtual ObjectResult<pa_ReporteArchivo_CUSPP_Result> pa_ReporteArchivo_CUSPP(string cUSPP, Nullable<int> archivoId)
    {

        var cUSPPParameter = cUSPP != null ?
            new ObjectParameter("CUSPP", cUSPP) :
            new ObjectParameter("CUSPP", typeof(string));


        var archivoIdParameter = archivoId.HasValue ?
            new ObjectParameter("ArchivoId", archivoId) :
            new ObjectParameter("ArchivoId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ReporteArchivo_CUSPP_Result>("pa_ReporteArchivo_CUSPP", cUSPPParameter, archivoIdParameter);
    }


    public virtual ObjectResult<pa_rpt_archivocarga_fecha_Result> pa_rpt_archivocarga_fecha(Nullable<int> tipo, Nullable<System.DateTime> fechainicio, Nullable<System.DateTime> fechatermino)
    {

        var tipoParameter = tipo.HasValue ?
            new ObjectParameter("tipo", tipo) :
            new ObjectParameter("tipo", typeof(int));


        var fechainicioParameter = fechainicio.HasValue ?
            new ObjectParameter("fechainicio", fechainicio) :
            new ObjectParameter("fechainicio", typeof(System.DateTime));


        var fechaterminoParameter = fechatermino.HasValue ?
            new ObjectParameter("fechatermino", fechatermino) :
            new ObjectParameter("fechatermino", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_rpt_archivocarga_fecha_Result>("pa_rpt_archivocarga_fecha", tipoParameter, fechainicioParameter, fechaterminoParameter);
    }


    public virtual ObjectResult<pa_rptNominas_Result> pa_rptNominas()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_rptNominas_Result>("pa_rptNominas");
    }


    public virtual int pa_rptPrimas(string periodo)
    {

        var periodoParameter = periodo != null ?
            new ObjectParameter("periodo", periodo) :
            new ObjectParameter("periodo", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_rptPrimas", periodoParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_CodigoTransferenciaNomina(string valor, Nullable<int> idArchivo, Nullable<int> largoCampo)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        var idArchivoParameter = idArchivo.HasValue ?
            new ObjectParameter("IdArchivo", idArchivo) :
            new ObjectParameter("IdArchivo", typeof(int));


        var largoCampoParameter = largoCampo.HasValue ?
            new ObjectParameter("LargoCampo", largoCampo) :
            new ObjectParameter("LargoCampo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_CodigoTransferenciaNomina", valorParameter, idArchivoParameter, largoCampoParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_CUSPP(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_CUSPP", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_EjecutaProcedimientoAlmacenado(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_EjecutaProcedimientoAlmacenado", valorParameter);
    }


    public virtual ObjectResult<string> pa_valida_EjecutaQuery(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_valida_EjecutaQuery", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Fecha(string valor, Nullable<System.DateTime> inicio)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("Inicio", inicio) :
            new ObjectParameter("Inicio", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Fecha", valorParameter, inicioParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_MontoAlto(Nullable<int> idarchivo, Nullable<int> idusuario)
    {

        var idarchivoParameter = idarchivo.HasValue ?
            new ObjectParameter("idarchivo", idarchivo) :
            new ObjectParameter("idarchivo", typeof(int));


        var idusuarioParameter = idusuario.HasValue ?
            new ObjectParameter("idusuario", idusuario) :
            new ObjectParameter("idusuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_MontoAlto", idarchivoParameter, idusuarioParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_NoEspacios(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_NoEspacios", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Numero12x2(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero12x2", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Numero2x2(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero2x2", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Numero4x7(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero4x7", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Numero7x2(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero7x2", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Numero8x2(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero8x2", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_ObtieneValor(Nullable<int> idArchivo, Nullable<int> numeroLinea, Nullable<int> campoInicial, Nullable<int> largoCampo, string valor)
    {

        var idArchivoParameter = idArchivo.HasValue ?
            new ObjectParameter("IdArchivo", idArchivo) :
            new ObjectParameter("IdArchivo", typeof(int));


        var numeroLineaParameter = numeroLinea.HasValue ?
            new ObjectParameter("NumeroLinea", numeroLinea) :
            new ObjectParameter("NumeroLinea", typeof(int));


        var campoInicialParameter = campoInicial.HasValue ?
            new ObjectParameter("CampoInicial", campoInicial) :
            new ObjectParameter("CampoInicial", typeof(int));


        var largoCampoParameter = largoCampo.HasValue ?
            new ObjectParameter("LargoCampo", largoCampo) :
            new ObjectParameter("LargoCampo", typeof(int));


        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_ObtieneValor", idArchivoParameter, numeroLineaParameter, campoInicialParameter, largoCampoParameter, valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Periodo(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Periodo", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_Periodo_PrimaPag(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Periodo_PrimaPag", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_persona(string primerNombre, string segundoNombre, string apellidoPaterno, string apellidoMaterno, Nullable<System.DateTime> fechaNacimiento, string cUSPP)
    {

        var primerNombreParameter = primerNombre != null ?
            new ObjectParameter("PrimerNombre", primerNombre) :
            new ObjectParameter("PrimerNombre", typeof(string));


        var segundoNombreParameter = segundoNombre != null ?
            new ObjectParameter("SegundoNombre", segundoNombre) :
            new ObjectParameter("SegundoNombre", typeof(string));


        var apellidoPaternoParameter = apellidoPaterno != null ?
            new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
            new ObjectParameter("ApellidoPaterno", typeof(string));


        var apellidoMaternoParameter = apellidoMaterno != null ?
            new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
            new ObjectParameter("ApellidoMaterno", typeof(string));


        var fechaNacimientoParameter = fechaNacimiento.HasValue ?
            new ObjectParameter("FechaNacimiento", fechaNacimiento) :
            new ObjectParameter("FechaNacimiento", typeof(System.DateTime));


        var cUSPPParameter = cUSPP != null ?
            new ObjectParameter("CUSPP", cUSPP) :
            new ObjectParameter("CUSPP", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_persona", primerNombreParameter, segundoNombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, fechaNacimientoParameter, cUSPPParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_RetornaTrue()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_RetornaTrue");
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_SoloNumeros(string valor)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_SoloNumeros", valorParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_SumaDetalleEnTotal(string valor, Nullable<int> idArchivo, Nullable<int> numeroLinea, Nullable<int> campoInicial, Nullable<int> largoCampo)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        var idArchivoParameter = idArchivo.HasValue ?
            new ObjectParameter("IdArchivo", idArchivo) :
            new ObjectParameter("IdArchivo", typeof(int));


        var numeroLineaParameter = numeroLinea.HasValue ?
            new ObjectParameter("NumeroLinea", numeroLinea) :
            new ObjectParameter("NumeroLinea", typeof(int));


        var campoInicialParameter = campoInicial.HasValue ?
            new ObjectParameter("CampoInicial", campoInicial) :
            new ObjectParameter("CampoInicial", typeof(int));


        var largoCampoParameter = largoCampo.HasValue ?
            new ObjectParameter("LargoCampo", largoCampo) :
            new ObjectParameter("LargoCampo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_SumaDetalleEnTotal", valorParameter, idArchivoParameter, numeroLineaParameter, campoInicialParameter, largoCampoParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_valida_TotalNominaEnLiquidacion(string valor, Nullable<int> idArchivo, Nullable<int> numeroLinea, Nullable<int> campoInicial, Nullable<int> largoCampo)
    {

        var valorParameter = valor != null ?
            new ObjectParameter("valor", valor) :
            new ObjectParameter("valor", typeof(string));


        var idArchivoParameter = idArchivo.HasValue ?
            new ObjectParameter("IdArchivo", idArchivo) :
            new ObjectParameter("IdArchivo", typeof(int));


        var numeroLineaParameter = numeroLinea.HasValue ?
            new ObjectParameter("NumeroLinea", numeroLinea) :
            new ObjectParameter("NumeroLinea", typeof(int));


        var campoInicialParameter = campoInicial.HasValue ?
            new ObjectParameter("CampoInicial", campoInicial) :
            new ObjectParameter("CampoInicial", typeof(int));


        var largoCampoParameter = largoCampo.HasValue ?
            new ObjectParameter("LargoCampo", largoCampo) :
            new ObjectParameter("LargoCampo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_TotalNominaEnLiquidacion", valorParameter, idArchivoParameter, numeroLineaParameter, campoInicialParameter, largoCampoParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_Valida_RangoFechaXContrato(Nullable<System.DateTime> date1, Nullable<System.DateTime> date2)
    {

        var date1Parameter = date1.HasValue ?
            new ObjectParameter("date1", date1) :
            new ObjectParameter("date1", typeof(System.DateTime));


        var date2Parameter = date2.HasValue ?
            new ObjectParameter("date2", date2) :
            new ObjectParameter("date2", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_Valida_RangoFechaXContrato", date1Parameter, date2Parameter);
    }


    public virtual int pa_upd_ApruebaLinCabNomina(Nullable<int> idContrato, Nullable<int> idHistoriaLinCab)
    {

        var idContratoParameter = idContrato.HasValue ?
            new ObjectParameter("IdContrato", idContrato) :
            new ObjectParameter("IdContrato", typeof(int));


        var idHistoriaLinCabParameter = idHistoriaLinCab.HasValue ?
            new ObjectParameter("IdHistoriaLinCab", idHistoriaLinCab) :
            new ObjectParameter("IdHistoriaLinCab", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_upd_ApruebaLinCabNomina", idContratoParameter, idHistoriaLinCabParameter);
    }


    public virtual int pa_upd_cambiaEstadoNomina(Nullable<int> idArchivoNomina, Nullable<int> idContrato)
    {

        var idArchivoNominaParameter = idArchivoNomina.HasValue ?
            new ObjectParameter("IdArchivoNomina", idArchivoNomina) :
            new ObjectParameter("IdArchivoNomina", typeof(int));


        var idContratoParameter = idContrato.HasValue ?
            new ObjectParameter("IdContrato", idContrato) :
            new ObjectParameter("IdContrato", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_upd_cambiaEstadoNomina", idArchivoNominaParameter, idContratoParameter);
    }


    public virtual int pa_upd_InactivaLinCabNomina(Nullable<int> idContrato, Nullable<int> idHistoriaLinCab)
    {

        var idContratoParameter = idContrato.HasValue ?
            new ObjectParameter("IdContrato", idContrato) :
            new ObjectParameter("IdContrato", typeof(int));


        var idHistoriaLinCabParameter = idHistoriaLinCab.HasValue ?
            new ObjectParameter("IdHistoriaLinCab", idHistoriaLinCab) :
            new ObjectParameter("IdHistoriaLinCab", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_upd_InactivaLinCabNomina", idContratoParameter, idHistoriaLinCabParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_Valida_RangoFechaXContratoV2(Nullable<System.DateTime> date1, Nullable<System.DateTime> date2)
    {

        var date1Parameter = date1.HasValue ?
            new ObjectParameter("date1", date1) :
            new ObjectParameter("date1", typeof(System.DateTime));


        var date2Parameter = date2.HasValue ?
            new ObjectParameter("date2", date2) :
            new ObjectParameter("date2", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_Valida_RangoFechaXContratoV2", date1Parameter, date2Parameter);
    }


    public virtual ObjectResult<pa_sel_pagoNominaApruebaDetalle_Result> pa_sel_pagoNominaApruebaDetalle(Nullable<int> idHistoriaLinCab)
    {

        var idHistoriaLinCabParameter = idHistoriaLinCab.HasValue ?
            new ObjectParameter("IdHistoriaLinCab", idHistoriaLinCab) :
            new ObjectParameter("IdHistoriaLinCab", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_pagoNominaApruebaDetalle_Result>("pa_sel_pagoNominaApruebaDetalle", idHistoriaLinCabParameter);
    }


    public virtual ObjectResult<pa_file_ObtieneReglasArchivoPorLinea_Result> pa_file_ObtieneReglasArchivoPorLinea(string param_TipoArchivo, string param_TipoLinea, Nullable<int> num_Contrato)
    {

        var param_TipoArchivoParameter = param_TipoArchivo != null ?
            new ObjectParameter("Param_TipoArchivo", param_TipoArchivo) :
            new ObjectParameter("Param_TipoArchivo", typeof(string));


        var param_TipoLineaParameter = param_TipoLinea != null ?
            new ObjectParameter("Param_TipoLinea", param_TipoLinea) :
            new ObjectParameter("Param_TipoLinea", typeof(string));


        var num_ContratoParameter = num_Contrato.HasValue ?
            new ObjectParameter("Num_Contrato", num_Contrato) :
            new ObjectParameter("Num_Contrato", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_file_ObtieneReglasArchivoPorLinea_Result>("pa_file_ObtieneReglasArchivoPorLinea", param_TipoArchivoParameter, param_TipoLineaParameter, num_ContratoParameter);
    }


    public virtual ObjectResult<pa_file_CantidadRegistroArchivo_Result> pa_file_CantidadRegistroArchivo(Nullable<int> idArchivo)
    {

        var idArchivoParameter = idArchivo.HasValue ?
            new ObjectParameter("IdArchivo", idArchivo) :
            new ObjectParameter("IdArchivo", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_file_CantidadRegistroArchivo_Result>("pa_file_CantidadRegistroArchivo", idArchivoParameter);
    }


    public virtual ObjectResult<pa_sel_historiaLinDetXArchivo_Result> pa_sel_historiaLinDetXArchivo(string nombreArchivo, Nullable<int> ideContrato, Nullable<int> cumpleValidacion)
    {

        var nombreArchivoParameter = nombreArchivo != null ?
            new ObjectParameter("NombreArchivo", nombreArchivo) :
            new ObjectParameter("NombreArchivo", typeof(string));


        var ideContratoParameter = ideContrato.HasValue ?
            new ObjectParameter("IdeContrato", ideContrato) :
            new ObjectParameter("IdeContrato", typeof(int));


        var cumpleValidacionParameter = cumpleValidacion.HasValue ?
            new ObjectParameter("CumpleValidacion", cumpleValidacion) :
            new ObjectParameter("CumpleValidacion", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_historiaLinDetXArchivo_Result>("pa_sel_historiaLinDetXArchivo", nombreArchivoParameter, ideContratoParameter, cumpleValidacionParameter);
    }


    public virtual ObjectResult<pa_sel_NominaForTelebankinByArchivoId_Result> pa_sel_NominaForTelebankinByArchivoId(Nullable<int> archivoId)
    {

        var archivoIdParameter = archivoId.HasValue ?
            new ObjectParameter("ArchivoId", archivoId) :
            new ObjectParameter("ArchivoId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_NominaForTelebankinByArchivoId_Result>("pa_sel_NominaForTelebankinByArchivoId", archivoIdParameter);
    }


    public virtual ObjectResult<pa_sel_nominaXArchivo_Result> pa_sel_nominaXArchivo(Nullable<int> ideContrato, string nombreArchivo, Nullable<long> cumpleValidacion)
    {

        var ideContratoParameter = ideContrato.HasValue ?
            new ObjectParameter("IdeContrato", ideContrato) :
            new ObjectParameter("IdeContrato", typeof(int));


        var nombreArchivoParameter = nombreArchivo != null ?
            new ObjectParameter("NombreArchivo", nombreArchivo) :
            new ObjectParameter("NombreArchivo", typeof(string));


        var cumpleValidacionParameter = cumpleValidacion.HasValue ?
            new ObjectParameter("CumpleValidacion", cumpleValidacion) :
            new ObjectParameter("CumpleValidacion", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_nominaXArchivo_Result>("pa_sel_nominaXArchivo", ideContratoParameter, nombreArchivoParameter, cumpleValidacionParameter);
    }


    public virtual ObjectResult<Nullable<int>> pa_copia_reglaArchivo(Nullable<int> nroContrato)
    {

        var nroContratoParameter = nroContrato.HasValue ?
            new ObjectParameter("NroContrato", nroContrato) :
            new ObjectParameter("NroContrato", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_copia_reglaArchivo", nroContratoParameter);
    }


    public virtual int pa_create_cuenta_26_export_sis(Nullable<int> archivoNominaId, Nullable<int> numeroAsiento, string tipoArchivo)
    {

        var archivoNominaIdParameter = archivoNominaId.HasValue ?
            new ObjectParameter("ArchivoNominaId", archivoNominaId) :
            new ObjectParameter("ArchivoNominaId", typeof(int));


        var numeroAsientoParameter = numeroAsiento.HasValue ?
            new ObjectParameter("NumeroAsiento", numeroAsiento) :
            new ObjectParameter("NumeroAsiento", typeof(int));


        var tipoArchivoParameter = tipoArchivo != null ?
            new ObjectParameter("TipoArchivo", tipoArchivo) :
            new ObjectParameter("TipoArchivo", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_create_cuenta_26_export_sis", archivoNominaIdParameter, numeroAsientoParameter, tipoArchivoParameter);
    }


    public virtual ObjectResult<pa_sel_NominaForTelebanking_Result> pa_sel_NominaForTelebanking(Nullable<int> ideContrato, Nullable<System.DateTime> fechaCarga, string estado)
    {

        var ideContratoParameter = ideContrato.HasValue ?
            new ObjectParameter("IdeContrato", ideContrato) :
            new ObjectParameter("IdeContrato", typeof(int));


        var fechaCargaParameter = fechaCarga.HasValue ?
            new ObjectParameter("FechaCarga", fechaCarga) :
            new ObjectParameter("FechaCarga", typeof(System.DateTime));


        var estadoParameter = estado != null ?
            new ObjectParameter("Estado", estado) :
            new ObjectParameter("Estado", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_NominaForTelebanking_Result>("pa_sel_NominaForTelebanking", ideContratoParameter, fechaCargaParameter, estadoParameter);
    }


    public virtual int pa_confirmaPagoNomina(Nullable<int> archivoId, Nullable<int> column)
    {

        var archivoIdParameter = archivoId.HasValue ?
            new ObjectParameter("ArchivoId", archivoId) :
            new ObjectParameter("ArchivoId", typeof(int));


        var columnParameter = column.HasValue ?
            new ObjectParameter("Column", column) :
            new ObjectParameter("Column", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_confirmaPagoNomina", archivoIdParameter, columnParameter);
    }


    public virtual ObjectResult<pa_sel_LogOperacion_Result> pa_sel_LogOperacion(Nullable<int> ideContrato, string tipoEvento, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string descripcion)
    {

        var ideContratoParameter = ideContrato.HasValue ?
            new ObjectParameter("IdeContrato", ideContrato) :
            new ObjectParameter("IdeContrato", typeof(int));


        var tipoEventoParameter = tipoEvento != null ?
            new ObjectParameter("TipoEvento", tipoEvento) :
            new ObjectParameter("TipoEvento", typeof(string));


        var fechaInicioParameter = fechaInicio.HasValue ?
            new ObjectParameter("FechaInicio", fechaInicio) :
            new ObjectParameter("FechaInicio", typeof(System.DateTime));


        var fechaFinParameter = fechaFin.HasValue ?
            new ObjectParameter("FechaFin", fechaFin) :
            new ObjectParameter("FechaFin", typeof(System.DateTime));


        var descripcionParameter = descripcion != null ?
            new ObjectParameter("Descripcion", descripcion) :
            new ObjectParameter("Descripcion", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_LogOperacion_Result>("pa_sel_LogOperacion", ideContratoParameter, tipoEventoParameter, fechaInicioParameter, fechaFinParameter, descripcionParameter);
    }


    public virtual ObjectResult<pa_sel_pagoNominaAprueba_Result> pa_sel_pagoNominaAprueba(Nullable<int> ideContrato, string nombreTipoArchivo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
    {

        var ideContratoParameter = ideContrato.HasValue ?
            new ObjectParameter("IdeContrato", ideContrato) :
            new ObjectParameter("IdeContrato", typeof(int));


        var nombreTipoArchivoParameter = nombreTipoArchivo != null ?
            new ObjectParameter("NombreTipoArchivo", nombreTipoArchivo) :
            new ObjectParameter("NombreTipoArchivo", typeof(string));


        var fechaInicioParameter = fechaInicio.HasValue ?
            new ObjectParameter("FechaInicio", fechaInicio) :
            new ObjectParameter("FechaInicio", typeof(System.DateTime));


        var fechaFinParameter = fechaFin.HasValue ?
            new ObjectParameter("FechaFin", fechaFin) :
            new ObjectParameter("FechaFin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_pagoNominaAprueba_Result>("pa_sel_pagoNominaAprueba", ideContratoParameter, nombreTipoArchivoParameter, fechaInicioParameter, fechaFinParameter);
    }


    public virtual ObjectResult<string> pa_create_cuenta_42_26_sis(Nullable<int> exactusCabeceraId, string asiento, Nullable<int> archivoNominaId, Nullable<int> numeroAsiento)
    {

        var exactusCabeceraIdParameter = exactusCabeceraId.HasValue ?
            new ObjectParameter("ExactusCabeceraId", exactusCabeceraId) :
            new ObjectParameter("ExactusCabeceraId", typeof(int));


        var asientoParameter = asiento != null ?
            new ObjectParameter("Asiento", asiento) :
            new ObjectParameter("Asiento", typeof(string));


        var archivoNominaIdParameter = archivoNominaId.HasValue ?
            new ObjectParameter("ArchivoNominaId", archivoNominaId) :
            new ObjectParameter("ArchivoNominaId", typeof(int));


        var numeroAsientoParameter = numeroAsiento.HasValue ?
            new ObjectParameter("NumeroAsiento", numeroAsiento) :
            new ObjectParameter("NumeroAsiento", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_create_cuenta_42_26_sis", exactusCabeceraIdParameter, asientoParameter, archivoNominaIdParameter, numeroAsientoParameter);
    }


    public virtual ObjectResult<pa_sel_historiaCargaArchivoLinDet_Result> pa_sel_historiaCargaArchivoLinDet(string nombreTipoArchivo, Nullable<int> iDE_CONTRATO, string cOD_AFP, string cOD_CUSP, string pRI_NOMB_PEN, string aPE_MATE_PEN, string nUM_DOCU_PEN, string nUM_SOLI_PEN, string tIP_MONE, Nullable<System.DateTime> fEC_PAGO_INI, Nullable<System.DateTime> fEC_PAGO_FIN, Nullable<System.DateTime> fechaAprobacionInicio, Nullable<System.DateTime> fechaAprobacionHasta, string estado)
    {

        var nombreTipoArchivoParameter = nombreTipoArchivo != null ?
            new ObjectParameter("NombreTipoArchivo", nombreTipoArchivo) :
            new ObjectParameter("NombreTipoArchivo", typeof(string));


        var iDE_CONTRATOParameter = iDE_CONTRATO.HasValue ?
            new ObjectParameter("IDE_CONTRATO", iDE_CONTRATO) :
            new ObjectParameter("IDE_CONTRATO", typeof(int));


        var cOD_AFPParameter = cOD_AFP != null ?
            new ObjectParameter("COD_AFP", cOD_AFP) :
            new ObjectParameter("COD_AFP", typeof(string));


        var cOD_CUSPParameter = cOD_CUSP != null ?
            new ObjectParameter("COD_CUSP", cOD_CUSP) :
            new ObjectParameter("COD_CUSP", typeof(string));


        var pRI_NOMB_PENParameter = pRI_NOMB_PEN != null ?
            new ObjectParameter("PRI_NOMB_PEN", pRI_NOMB_PEN) :
            new ObjectParameter("PRI_NOMB_PEN", typeof(string));


        var aPE_MATE_PENParameter = aPE_MATE_PEN != null ?
            new ObjectParameter("APE_MATE_PEN", aPE_MATE_PEN) :
            new ObjectParameter("APE_MATE_PEN", typeof(string));


        var nUM_DOCU_PENParameter = nUM_DOCU_PEN != null ?
            new ObjectParameter("NUM_DOCU_PEN", nUM_DOCU_PEN) :
            new ObjectParameter("NUM_DOCU_PEN", typeof(string));


        var nUM_SOLI_PENParameter = nUM_SOLI_PEN != null ?
            new ObjectParameter("NUM_SOLI_PEN", nUM_SOLI_PEN) :
            new ObjectParameter("NUM_SOLI_PEN", typeof(string));


        var tIP_MONEParameter = tIP_MONE != null ?
            new ObjectParameter("TIP_MONE", tIP_MONE) :
            new ObjectParameter("TIP_MONE", typeof(string));


        var fEC_PAGO_INIParameter = fEC_PAGO_INI.HasValue ?
            new ObjectParameter("FEC_PAGO_INI", fEC_PAGO_INI) :
            new ObjectParameter("FEC_PAGO_INI", typeof(System.DateTime));


        var fEC_PAGO_FINParameter = fEC_PAGO_FIN.HasValue ?
            new ObjectParameter("FEC_PAGO_FIN", fEC_PAGO_FIN) :
            new ObjectParameter("FEC_PAGO_FIN", typeof(System.DateTime));


        var fechaAprobacionInicioParameter = fechaAprobacionInicio.HasValue ?
            new ObjectParameter("FechaAprobacionInicio", fechaAprobacionInicio) :
            new ObjectParameter("FechaAprobacionInicio", typeof(System.DateTime));


        var fechaAprobacionHastaParameter = fechaAprobacionHasta.HasValue ?
            new ObjectParameter("FechaAprobacionHasta", fechaAprobacionHasta) :
            new ObjectParameter("FechaAprobacionHasta", typeof(System.DateTime));


        var estadoParameter = estado != null ?
            new ObjectParameter("Estado", estado) :
            new ObjectParameter("Estado", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_historiaCargaArchivoLinDet_Result>("pa_sel_historiaCargaArchivoLinDet", nombreTipoArchivoParameter, iDE_CONTRATOParameter, cOD_AFPParameter, cOD_CUSPParameter, pRI_NOMB_PENParameter, aPE_MATE_PENParameter, nUM_DOCU_PENParameter, nUM_SOLI_PENParameter, tIP_MONEParameter, fEC_PAGO_INIParameter, fEC_PAGO_FINParameter, fechaAprobacionInicioParameter, fechaAprobacionHastaParameter, estadoParameter);
    }


    public virtual ObjectResult<pa_sel_nominaConsulta_Result> pa_sel_nominaConsulta(string nombreTipoArchivo, Nullable<int> contratoId, string nombreBene, Nullable<short> monedaId, string estado, Nullable<System.DateTime> fechaCreacionInicio, Nullable<System.DateTime> fechaCreacionFin, Nullable<System.DateTime> fechaAprobacionInicio, Nullable<System.DateTime> fechaAprobacionFin)
    {

        var nombreTipoArchivoParameter = nombreTipoArchivo != null ?
            new ObjectParameter("NombreTipoArchivo", nombreTipoArchivo) :
            new ObjectParameter("NombreTipoArchivo", typeof(string));


        var contratoIdParameter = contratoId.HasValue ?
            new ObjectParameter("ContratoId", contratoId) :
            new ObjectParameter("ContratoId", typeof(int));


        var nombreBeneParameter = nombreBene != null ?
            new ObjectParameter("NombreBene", nombreBene) :
            new ObjectParameter("NombreBene", typeof(string));


        var monedaIdParameter = monedaId.HasValue ?
            new ObjectParameter("MonedaId", monedaId) :
            new ObjectParameter("MonedaId", typeof(short));


        var estadoParameter = estado != null ?
            new ObjectParameter("Estado", estado) :
            new ObjectParameter("Estado", typeof(string));


        var fechaCreacionInicioParameter = fechaCreacionInicio.HasValue ?
            new ObjectParameter("FechaCreacionInicio", fechaCreacionInicio) :
            new ObjectParameter("FechaCreacionInicio", typeof(System.DateTime));


        var fechaCreacionFinParameter = fechaCreacionFin.HasValue ?
            new ObjectParameter("FechaCreacionFin", fechaCreacionFin) :
            new ObjectParameter("FechaCreacionFin", typeof(System.DateTime));


        var fechaAprobacionInicioParameter = fechaAprobacionInicio.HasValue ?
            new ObjectParameter("FechaAprobacionInicio", fechaAprobacionInicio) :
            new ObjectParameter("FechaAprobacionInicio", typeof(System.DateTime));


        var fechaAprobacionFinParameter = fechaAprobacionFin.HasValue ?
            new ObjectParameter("FechaAprobacionFin", fechaAprobacionFin) :
            new ObjectParameter("FechaAprobacionFin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_nominaConsulta_Result>("pa_sel_nominaConsulta", nombreTipoArchivoParameter, contratoIdParameter, nombreBeneParameter, monedaIdParameter, estadoParameter, fechaCreacionInicioParameter, fechaCreacionFinParameter, fechaAprobacionInicioParameter, fechaAprobacionFinParameter);
    }


    public virtual ObjectResult<pa_sel_SegDescarga_Result> pa_sel_SegDescarga(Nullable<int> ideContrato, string nombreTipoArchivo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<System.DateTime> fechaInicioAprobacion, Nullable<System.DateTime> fechaFinAprobacion)
    {

        var ideContratoParameter = ideContrato.HasValue ?
            new ObjectParameter("IdeContrato", ideContrato) :
            new ObjectParameter("IdeContrato", typeof(int));


        var nombreTipoArchivoParameter = nombreTipoArchivo != null ?
            new ObjectParameter("NombreTipoArchivo", nombreTipoArchivo) :
            new ObjectParameter("NombreTipoArchivo", typeof(string));


        var fechaInicioParameter = fechaInicio.HasValue ?
            new ObjectParameter("FechaInicio", fechaInicio) :
            new ObjectParameter("FechaInicio", typeof(System.DateTime));


        var fechaFinParameter = fechaFin.HasValue ?
            new ObjectParameter("FechaFin", fechaFin) :
            new ObjectParameter("FechaFin", typeof(System.DateTime));


        var fechaInicioAprobacionParameter = fechaInicioAprobacion.HasValue ?
            new ObjectParameter("FechaInicioAprobacion", fechaInicioAprobacion) :
            new ObjectParameter("FechaInicioAprobacion", typeof(System.DateTime));


        var fechaFinAprobacionParameter = fechaFinAprobacion.HasValue ?
            new ObjectParameter("FechaFinAprobacion", fechaFinAprobacion) :
            new ObjectParameter("FechaFinAprobacion", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_sel_SegDescarga_Result>("pa_sel_SegDescarga", ideContratoParameter, nombreTipoArchivoParameter, fechaInicioParameter, fechaFinParameter, fechaInicioAprobacionParameter, fechaFinAprobacionParameter);
    }

}

}

