//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoSolicitados
    {
        public int DocumentoSolicitadoId { get; set; }
        public int TipoMovimientoId { get; set; }
        public int DocumentoId { get; set; }
        public Nullable<int> TipoSolicitudId { get; set; }
    
        public virtual Documentos Documentos { get; set; }
        public virtual TipoMovimientos TipoMovimientos { get; set; }
    }
}
