//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public Documentos()
        {
            this.Checkeados = new HashSet<Checkeados>();
            this.DocumentoSolicitados = new HashSet<DocumentoSolicitados>();
        }
    
        public int DocumentoId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Checkeados> Checkeados { get; set; }
        public virtual ICollection<DocumentoSolicitados> DocumentoSolicitados { get; set; }
    }
}
