
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Evento
{

    public string CodiEven { get; set; }

    public string TipoEven { get; set; }

    public string DescEven { get; set; }

    public string AbreEven { get; set; }

    public string EstEven { get; set; }

}

}
