
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class EXACTUS_CABECERA
{

    public string NRO_CONTRATO { get; set; }

    public string TIPO_INFO { get; set; }

    public int ANIO_VIGENTE { get; set; }

    public int MES_VIGENTE { get; set; }

    public string ASIENTO { get; set; }

    public string PAQUETE { get; set; }

    public string TIPO_ASIENTO { get; set; }

    public System.DateTime FECHA { get; set; }

    public string CONTABILIDAD { get; set; }

    public string NOTAS { get; set; }

    public int ESTADO { get; set; }

    public string ESTADO_TRANSFERENCIA { get; set; }

    public string PERMITIR_DESCUADRADO { get; set; }

    public string CONSERVAR_NUMERACION { get; set; }

    public string ACTUALIZAR_CONSECUTIVO { get; set; }

    public Nullable<System.DateTime> FECHA_AUDITORIA { get; set; }

    public System.DateTime FECHA_CREACION { get; set; }

    public string USUARIO_REGISTRO { get; set; }

}

}
