
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class EXACTUS_CABECERA_SIS
{

    public EXACTUS_CABECERA_SIS()
    {

        this.EXACTUS_DETALLE_SIS = new HashSet<EXACTUS_DETALLE_SIS>();

    }


    public int IDE_EXACTUS_CABECERA_SIS { get; set; }

    public int IDE_CONTRATO { get; set; }

    public int ArchivoId { get; set; }

    public string TIPO_ARCHIVO { get; set; }

    public Nullable<int> IDE_MONEDA { get; set; }

    public string ASIENTO { get; set; }

    public string PAQUETE { get; set; }

    public string TIPO_ASIENTO { get; set; }

    public System.DateTime FECHA { get; set; }

    public string CONTABILIDAD { get; set; }

    public string NOTAS { get; set; }

    public int ESTADO { get; set; }

    public string ESTADO_TRANSFERENCIA { get; set; }

    public string PERMITIR_DESCUADRADO { get; set; }

    public string CONSERVAR_NUMERACION { get; set; }

    public string ACTUALIZAR_CONSECUTIVO { get; set; }

    public Nullable<System.DateTime> FECHA_AUDITORIA { get; set; }

    public System.DateTime FECHA_CREACION { get; set; }

    public string USUARIO_REGISTRO { get; set; }



    public virtual CONTRATO_SYS CONTRATO_SYS { get; set; }

    public virtual Archivo Archivo { get; set; }

    public virtual ICollection<EXACTUS_DETALLE_SIS> EXACTUS_DETALLE_SIS { get; set; }

}

}
