
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class EXACTUS_DETALLE_EXPORT_SIS
{

    public int IDE_CONTRATO { get; set; }

    public int ArchivoId { get; set; }

    public string TIPO_ARHIVO { get; set; }

    public int IDE_MONEDA { get; set; }

    public string CUENTA_BANCARIA { get; set; }

    public int NUMERO { get; set; }

    public string TIPO_DOCUMENTO { get; set; }

    public System.DateTime FECHA_DOCUMENTO { get; set; }

    public string CONCEPTO { get; set; }

    public string BENEFICIARIO { get; set; }

    public string CONTRIBUYENTE { get; set; }

    public decimal MONTO { get; set; }

    public string DETALLE { get; set; }

    public decimal SUBTIPO { get; set; }

    public string CENTRO_COSTO { get; set; }

    public string CUENTA_CONTABLE { get; set; }

    public string RUBRO_1 { get; set; }

    public string RUBRO_2 { get; set; }

    public string RUBRO_3 { get; set; }

    public string RUBRO_4 { get; set; }

    public string RUBRO_5 { get; set; }

    public string PAQUETE { get; set; }



    public virtual CONTRATO_SYS CONTRATO_SYS { get; set; }

    public virtual Archivo Archivo { get; set; }

}

}
