
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class HistorialCargaArchivo_LinDet
{

    public long IdHistorialCargaArchivoLinDet { get; set; }

    public Nullable<long> IdHistorialCargaArchivoLinCab { get; set; }

    public Nullable<System.DateTime> FechaInsert { get; set; }

    public string TipoLinea { get; set; }

    public Nullable<int> NumeroLinea { get; set; }

    public Nullable<System.DateTime> FEC_DEVE { get; set; }

    public Nullable<System.DateTime> FEC_FALL { get; set; }

    public Nullable<System.DateTime> FEC_OCUR { get; set; }

    public Nullable<System.DateTime> FEC_PAGO_APO_ADI { get; set; }

    public Nullable<System.DateTime> FEC_INV_DEF { get; set; }

    public string CAP_GAST_SEP { get; set; }

    public string PARE { get; set; }

    public string SAL_CIC_SOL { get; set; }

    public string TIP_REGI { get; set; }

    public string TIP_SOLI { get; set; }

    public string NUM_BENE { get; set; }

    public string NUM_MESE_DEV { get; set; }

    public string POR_BENE { get; set; }

    public string TIP_IDEN_SOL { get; set; }

    public string TIP_PENS { get; set; }

    public string TIP_DOCU_IDE_PEN { get; set; }

    public string TIP_MOVI { get; set; }

    public string COD_CSV_01 { get; set; }

    public string COD_CSV_02 { get; set; }

    public string COD_CSV_03 { get; set; }

    public string COD_CSV_04 { get; set; }

    public string COD_CSV_05 { get; set; }

    public string COD_CSV_06 { get; set; }

    public string COD_CSV_07 { get; set; }

    public string COD_CSV_08 { get; set; }

    public string COD_AFP { get; set; }

    public string COD_IDE_CSV { get; set; }

    public string FRA_MESE_DEV { get; set; }

    public string IND_PENS_PRE { get; set; }

    public string MTO_PPRE_ORI { get; set; }

    public string TIP_CAMB_VTA { get; set; }

    public string EXC_PENS_SOL { get; set; }

    public string EXC_PENS_NM { get; set; }

    public string MES_DEVE { get; set; }

    public string CAP_REQU_PEN { get; set; }

    public string CRU_FAMI { get; set; }

    public string FEC_NACI { get; set; }

    public string FEC_NACI_PEN { get; set; }

    public string FEC_PAGO { get; set; }

    public string FEC_PAGO_TEX { get; set; }

    public string FEC_SECI { get; set; }

    public string FEC_SINI_OCU { get; set; }

    public string FEC_DEVE_ACT { get; set; }

    public string FEC_DEVE_INI { get; set; }

    public string FEC_FIN_SUB { get; set; }

    public string RAM_PROM_SOL { get; set; }

    public string TAS_INTE { get; set; }

    public string VACIO_10 { get; set; }

    public string DES_PENS_MONE { get; set; }

    public string MTO_APOR_ADI { get; set; }

    public string MTO_APOR_ADI_SOL { get; set; }

    public string MTO_APOR_COM { get; set; }

    public string MTO_PENS_PAG { get; set; }

    public string MTO_PPRE_MN { get; set; }

    public string MTO_APOR_OBL { get; set; }

    public string MTO_MONE_APO_COM1 { get; set; }

    public string MTO_MONE_APO_COM2 { get; set; }

    public string MTO_MONE_APO_COM3 { get; set; }

    public string MTO_MONE_APO_COM4 { get; set; }

    public string MTO_MONE_APO_COM5 { get; set; }

    public string MTO_MONE_APO_COM6 { get; set; }

    public string MTO_MONE_APO_COM7 { get; set; }

    public string MTO_MONE_APO_COM8 { get; set; }

    public string MTO_MONE_APO_OBL1 { get; set; }

    public string MTO_MONE_APO_OBL2 { get; set; }

    public string MTO_MONE_APO_OBL3 { get; set; }

    public string MTO_MONE_APO_OBL4 { get; set; }

    public string MTO_MONE_APO_OBL5 { get; set; }

    public string MTO_MONE_APO_OBL6 { get; set; }

    public string MTO_MONE_APO_OBL7 { get; set; }

    public string MTO_MONE_APO_OBL8 { get; set; }

    public string MTO_PAGO_REE_SOL { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP1 { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP2 { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP3 { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP4 { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP5 { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP6 { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP7 { get; set; }

    public string MTO_PRIM_PAG_PENS_AFP8 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP1 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP2 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP3 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP4 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP5 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP6 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP7 { get; set; }

    public string MTO_DSCT_PENS_PAG_AFP8 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP1 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP2 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP3 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP4 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP5 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP6 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP7 { get; set; }

    public string MTO_SOLE_APO_ADI_AFP8 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP1 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP2 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP3 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP4 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP5 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP6 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP7 { get; set; }

    public string MTO_SOLE_REE_PAG_AFP8 { get; set; }

    public string NRO_CSV { get; set; }

    public string NUM_DOCU_SOL { get; set; }

    public string NUM_SINI { get; set; }

    public string NUM_SOLI { get; set; }

    public string NUM_SOLI_PEN { get; set; }

    public string NUM_DOCU_PEN { get; set; }

    public string PEN_PAGA_MON { get; set; }

    public string PEN_BASE_MON { get; set; }

    public string REM_PROM_ACT { get; set; }

    public string NUM_APOR_ACT { get; set; }

    public string SAL_CIC_MN { get; set; }

    public string TIP_CAMB_COM { get; set; }

    public string TIP_MONE { get; set; }

    public string TOT_CAPI_REQ_MN { get; set; }

    public string TOT_CAPI_REQ_ORI { get; set; }

    public string COD_CUSP { get; set; }

    public string COD_BENE_MN { get; set; }

    public string APE_MATE_PEN { get; set; }

    public string APE_MATE_SOLI { get; set; }

    public string APE_PATE_PEN { get; set; }

    public string APE_PATE_SOL { get; set; }

    public string PRI_NOMB_PEN { get; set; }

    public string PRI_NOMB_SOL { get; set; }

    public string SEG_NOMB_PEN { get; set; }

    public string SEG_NOMB_SOL { get; set; }

    public string SUC_INTE { get; set; }

    public Nullable<int> CumpleValidacion { get; set; }

    public string ReglaObservada { get; set; }



    public virtual HistorialCargaArchivo_LinCab HistorialCargaArchivo_LinCab { get; set; }

}

}
