
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Moneda
{

    public Moneda()
    {

        this.TipoMonedas = new HashSet<TipoMoneda>();

        this.Pagos = new HashSet<Pago>();

    }


    public int MonedaId { get; set; }

    public string NombreMoneda { get; set; }



    public virtual ICollection<TipoMoneda> TipoMonedas { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; }

}

}
