
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class OPERACION
{

    public int NRO_OPERACION { get; set; }

    public string TIP_OPERACION { get; set; }

    public string TIPO_REGISTRO { get; set; }

    public string COD_REASEGURADOR { get; set; }

    public System.DateTime FEC_OPERACION { get; set; }

    public int ANO_OPERACION { get; set; }

    public int MES_OPERACION { get; set; }

    public string COD_ASEGURADO { get; set; }

    public string IDE_CONTRATO { get; set; }

    public string COD_RAMO { get; set; }

    public string COD_MONEDA { get; set; }

    public Nullable<decimal> TCA_CAMBIO { get; set; }

    public Nullable<decimal> ENTORNO_PRIMA_T_2 { get; set; }

    public Nullable<decimal> ENTORNO_PRIMA_T_1 { get; set; }

    public Nullable<decimal> PRIMA_ABONADA { get; set; }

    public Nullable<decimal> PRIMA_REG_CONTAB { get; set; }

    public Nullable<decimal> PRIMA_CED_BRUTA { get; set; }

    public Nullable<decimal> PRI_CED_MES { get; set; }

    public string DES_REG_MES { get; set; }

    public Nullable<decimal> IMP_IMPUESTO_MES { get; set; }

    public Nullable<decimal> PRI_XPAG_REA_CED { get; set; }

    public Nullable<decimal> PRI_XCOB_REA_ACE { get; set; }

    public Nullable<decimal> SIN_DIRECTO { get; set; }

    public Nullable<decimal> SIN_XCOB_REA_CED { get; set; }

    public Nullable<decimal> SIN_XPAG_REA_ACE { get; set; }

    public Nullable<decimal> OTR_CTA_XCOB_REA_CED { get; set; }

    public Nullable<decimal> OTR_CTA_XPAG_REA_ACE { get; set; }

    public Nullable<decimal> DSCTO_COMIS_REA { get; set; }

    public Nullable<decimal> SALDO_DEUDOR { get; set; }

    public Nullable<decimal> SALDO_ACREEDOR { get; set; }

    public string ESTADO { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public string USU_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }

    public string ORI_REG { get; set; }

    public string TIP_COMPROBANTE { get; set; }

    public Nullable<short> ORIGEN_OPERACION { get; set; }

}

}
