
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Pago
{

    public int PagoId { get; set; }

    public int ArchivoId { get; set; }

    public System.DateTime FechaIngreso { get; set; }

    public System.DateTime FechaPago { get; set; }

    public int Estado { get; set; }

    public int SiniestroId { get; set; }

    public decimal Monto { get; set; }

    public decimal PagoVC { get; set; }

    public System.DateTime FechaTransferencia { get; set; }

    public int MonedaId { get; set; }

    public int NominaId { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<bool> Vigente { get; set; }



    public virtual Moneda Moneda { get; set; }

    public virtual Siniestro Siniestro { get; set; }

}

}
