
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Parametro
{

    public int ParametroId { get; set; }

    public int TipoMovimientoId { get; set; }

    public int TipoSolicitudId { get; set; }

    public int TipoOperacion { get; set; }

    public string CentroCosto { get; set; }

    public string CuentaContable { get; set; }

    public string SignoCuenta { get; set; }

    public bool Vigente { get; set; }

}

}
