
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Parentesco
{

    public int ParentescoId { get; set; }

    public string DescripcionParentesco { get; set; }

    public string CodBeneficiario { get; set; }

    public int PorcentajeBeneficiario { get; set; }

}

}
