
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class TipoArchivo
{

    public TipoArchivo()
    {

        this.Archivoes = new HashSet<Archivo>();

    }


    public int TipoArchivoId { get; set; }

    public string NombreTipoArchivo { get; set; }

    public string NombreClase { get; set; }

    public byte EsEntrada { get; set; }

    public int CabeceraLargo { get; set; }

    public int DetalleLargo { get; set; }

    public int TotalLargo { get; set; }

    public string ReglaPrevia { get; set; }

    public string ReglaPosterior { get; set; }

    public Nullable<int> TipoInformeId { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<bool> Vigente { get; set; }



    public virtual ICollection<Archivo> Archivoes { get; set; }

    public virtual TipoInforme TipoInforme { get; set; }

}

}
