
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class TipoInforme
{

    public TipoInforme()
    {

        this.TipoArchivoes = new HashSet<TipoArchivo>();

    }


    public int TipoInformeId { get; set; }

    public string Nombre { get; set; }



    public virtual ICollection<TipoArchivo> TipoArchivoes { get; set; }

}

}
