
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class USUARIO
{

    public int IDE_USUARIO { get; set; }

    public string USUARIO1 { get; set; }

    public string CONTRASENA { get; set; }

    public string ACCESO_PAGINA { get; set; }

    public string NOMBRES { get; set; }

    public string CARGO { get; set; }

    public string EMAIL { get; set; }

    public string TIPO_USUARIO { get; set; }

    public string ESTADO { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public string USU_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }

}

}
